config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  get '/todos', to: "todos#index"

  get '/todos/:id', to: "todos#show"
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end 

	def show 
		@todo = Todo.find(params[:id])
	end 

	def new 
		@todo = Todo.new
	end 

  def create 
    @todo = Todo.create(todo_params)
  end 

  private 
    def todo_params
      params.require(:todo).permit(:title, :description)
    end 
    # return the title and description from new.html.erb
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1> A list of todos </h1>

<% @todos.each do |todo| %>
	<li><%=todo.title%></li>
<% end %> 

app/views/todos/new.html.erb
<h1> Create a new todo </h1>

<%= form_for @todo do |f| %>
	<%= label_tag(:title, "Title:") %>
	<%= f.text_field :title %></br> 

	<%= label_tag(:description, "Description:") %>
	<%= f.text_field :description %></br> 
	<%= f.submit "Create" %>

<% end %> 

app/views/todos/show.html.erb
<h1> Todo show page </h1> 
<p>Title: <%= @todo['title']%></p>
<p>Description: <%= @todo['description'] %></p>

<%= link_to "Back to Todo List",todos_path%> 